// GENERATED FILE — do not edit by hand.
// Source: packages/nanovdb-wgsl/vendor/stride-tables.json (NanoVDB ABI 32.9.1)
// Regenerate: node scripts/extract-stride-tables.mjs
// Guarded by: packages/nanovdb-wgsl/test/stride-tables-generated.test.ts

/**
 * Typed, browser-safe mirror of `../../vendor/stride-tables.json` — see
 * `./stride-tables.ts` for the accessor surface (defineNumber/defineBigInt/
 * gridTypeConstantsFor/gridTypeConstantsForId/etc.) built on top of this data.
 * Unlike the JSON file, importing this module never touches `node:fs`, so it
 * works in bundler/browser contexts (Vite pages, etc.) as well as Node.
 */
export const strideTables = {
  "$meta": {
    "repo": "https://github.com/AcademySoftwareFoundation/openvdb",
    "path": "nanovdb/nanovdb/PNanoVDB.h",
    "commit": "a532de5526ef791280b6483a872336a811a68542",
    "sha256": "083a61491472bd2b008d5c3406aea0b1ac047c031b251047a5e38dac29f17410",
    "abi": "32.9.1",
    "generatedBy": "scripts/extract-stride-tables.mjs"
  },
  "defines": {
    "PNANOVDB_FALSE": 0,
    "PNANOVDB_TRUE": 1,
    "PNANOVDB_MAGIC_NUMBER": "0x304244566f6e614e",
    "PNANOVDB_MAGIC_GRID": "0x314244566f6e614e",
    "PNANOVDB_MAGIC_FILE": "0x324244566f6e614e",
    "PNANOVDB_MAJOR_VERSION_NUMBER": 32,
    "PNANOVDB_MINOR_VERSION_NUMBER": 9,
    "PNANOVDB_PATCH_VERSION_NUMBER": 1,
    "PNANOVDB_GRID_TYPE_UNKNOWN": 0,
    "PNANOVDB_GRID_TYPE_FLOAT": 1,
    "PNANOVDB_GRID_TYPE_DOUBLE": 2,
    "PNANOVDB_GRID_TYPE_INT16": 3,
    "PNANOVDB_GRID_TYPE_INT32": 4,
    "PNANOVDB_GRID_TYPE_INT64": 5,
    "PNANOVDB_GRID_TYPE_VEC3F": 6,
    "PNANOVDB_GRID_TYPE_VEC3D": 7,
    "PNANOVDB_GRID_TYPE_MASK": 8,
    "PNANOVDB_GRID_TYPE_HALF": 9,
    "PNANOVDB_GRID_TYPE_UINT32": 10,
    "PNANOVDB_GRID_TYPE_BOOLEAN": 11,
    "PNANOVDB_GRID_TYPE_RGBA8": 12,
    "PNANOVDB_GRID_TYPE_FP4": 13,
    "PNANOVDB_GRID_TYPE_FP8": 14,
    "PNANOVDB_GRID_TYPE_FP16": 15,
    "PNANOVDB_GRID_TYPE_FPN": 16,
    "PNANOVDB_GRID_TYPE_VEC4F": 17,
    "PNANOVDB_GRID_TYPE_VEC4D": 18,
    "PNANOVDB_GRID_TYPE_INDEX": 19,
    "PNANOVDB_GRID_TYPE_ONINDEX": 20,
    "PNANOVDB_GRID_TYPE_POINTINDEX": 23,
    "PNANOVDB_GRID_TYPE_VEC3U8": 24,
    "PNANOVDB_GRID_TYPE_VEC3U16": 25,
    "PNANOVDB_GRID_TYPE_UINT8": 26,
    "PNANOVDB_GRID_TYPE_END": 27,
    "PNANOVDB_GRID_TYPE_CAP": 32,
    "PNANOVDB_GRID_CLASS_UNKNOWN": 0,
    "PNANOVDB_GRID_CLASS_LEVEL_SET": 1,
    "PNANOVDB_GRID_CLASS_FOG_VOLUME": 2,
    "PNANOVDB_GRID_CLASS_STAGGERED": 3,
    "PNANOVDB_GRID_CLASS_POINT_INDEX": 4,
    "PNANOVDB_GRID_CLASS_POINT_DATA": 5,
    "PNANOVDB_GRID_CLASS_TOPOLOGY": 6,
    "PNANOVDB_GRID_CLASS_VOXEL_VOLUME": 7,
    "PNANOVDB_GRID_CLASS_INDEX_GRID": 8,
    "PNANOVDB_GRID_CLASS_TENSOR_GRID": 9,
    "PNANOVDB_GRID_CLASS_VOXEL_BVH": 10,
    "PNANOVDB_GRID_CLASS_END": 11,
    "PNANOVDB_LEAF_TYPE_DEFAULT": 0,
    "PNANOVDB_LEAF_TYPE_LITE": 1,
    "PNANOVDB_LEAF_TYPE_FP": 2,
    "PNANOVDB_LEAF_TYPE_INDEX": 3,
    "PNANOVDB_LEAF_TYPE_POINTINDEX": 5,
    "PNANOVDB_MAP_SIZE": 264,
    "PNANOVDB_MAP_OFF_MATF": 0,
    "PNANOVDB_MAP_OFF_INVMATF": 36,
    "PNANOVDB_MAP_OFF_VECF": 72,
    "PNANOVDB_MAP_OFF_TAPERF": 84,
    "PNANOVDB_MAP_OFF_MATD": 88,
    "PNANOVDB_MAP_OFF_INVMATD": 160,
    "PNANOVDB_MAP_OFF_VECD": 232,
    "PNANOVDB_MAP_OFF_TAPERD": 256,
    "PNANOVDB_GRID_SIZE": 672,
    "PNANOVDB_GRID_OFF_MAGIC": 0,
    "PNANOVDB_GRID_OFF_CHECKSUM": 8,
    "PNANOVDB_GRID_OFF_VERSION": 16,
    "PNANOVDB_GRID_OFF_FLAGS": 20,
    "PNANOVDB_GRID_OFF_GRID_INDEX": 24,
    "PNANOVDB_GRID_OFF_GRID_COUNT": 28,
    "PNANOVDB_GRID_OFF_GRID_SIZE": 32,
    "PNANOVDB_GRID_OFF_GRID_NAME": 40,
    "PNANOVDB_GRID_OFF_MAP": 296,
    "PNANOVDB_GRID_OFF_WORLD_BBOX": 560,
    "PNANOVDB_GRID_OFF_VOXEL_SIZE": 608,
    "PNANOVDB_GRID_OFF_GRID_CLASS": 632,
    "PNANOVDB_GRID_OFF_GRID_TYPE": 636,
    "PNANOVDB_GRID_OFF_BLIND_METADATA_OFFSET": 640,
    "PNANOVDB_GRID_OFF_BLIND_METADATA_COUNT": 648,
    "PNANOVDB_GRID_OFF_DATA0": 652,
    "PNANOVDB_GRID_OFF_DATA1": 656,
    "PNANOVDB_GRID_OFF_DATA2": 664,
    "PNANOVDB_GRIDBLINDMETADATA_CLASS_UNKNOWN": 0,
    "PNANOVDB_GRIDBLINDMETADATA_CLASS_INDEX_ARRAY": 1,
    "PNANOVDB_GRIDBLINDMETADATA_CLASS_ATTRIBUTE_ARRAY": 2,
    "PNANOVDB_GRIDBLINDMETADATA_CLASS_GRID_NAME": 3,
    "PNANOVDB_GRIDBLINDMETADATA_CLASS_CHANNEL_ARRAY": 4,
    "PNANOVDB_GRIDBLINDMETADATA_CLASS_END": 5,
    "PNANOVDB_GRIDBLINDMETADATA_SEMANTIC_UNKNOWN": 0,
    "PNANOVDB_GRIDBLINDMETADATA_SEMANTIC_POINT_POSITION": 1,
    "PNANOVDB_GRIDBLINDMETADATA_SEMANTIC_POINT_COLOR": 2,
    "PNANOVDB_GRIDBLINDMETADATA_SEMANTIC_POINT_NORMAL": 3,
    "PNANOVDB_GRIDBLINDMETADATA_SEMANTIC_POINT_RADIUS": 4,
    "PNANOVDB_GRIDBLINDMETADATA_SEMANTIC_POINT_VELOCITY": 5,
    "PNANOVDB_GRIDBLINDMETADATA_SEMANTIC_POINT_ID": 6,
    "PNANOVDB_GRIDBLINDMETADATA_SEMANTIC_WORLD_COORDS": 7,
    "PNANOVDB_GRIDBLINDMETADATA_SEMANTIC_GRID_COORDS": 8,
    "PNANOVDB_GRIDBLINDMETADATA_SEMANTIC_VOXEL_COORDS": 9,
    "PNANOVDB_GRIDBLINDMETADATA_SEMANTIC_LEVEL_SET": 10,
    "PNANOVDB_GRIDBLINDMETADATA_SEMANTIC_FOG_VOLUME": 11,
    "PNANOVDB_GRIDBLINDMETADATA_SEMANTIC_STAGGERED": 12,
    "PNANOVDB_GRIDBLINDMETADATA_SEMANTIC_POINT_OPACITY": 13,
    "PNANOVDB_GRIDBLINDMETADATA_SEMANTIC_POINT_QUAT": 14,
    "PNANOVDB_GRIDBLINDMETADATA_SEMANTIC_POINT_SCALE": 15,
    "PNANOVDB_GRIDBLINDMETADATA_SEMANTIC_POINT_SH0": 16,
    "PNANOVDB_GRIDBLINDMETADATA_SEMANTIC_POINT_SHN": 17,
    "PNANOVDB_GRIDBLINDMETADATA_SEMANTIC_LINE_ID": 18,
    "PNANOVDB_GRIDBLINDMETADATA_SEMANTIC_TRIANGLE_ID": 19,
    "PNANOVDB_GRIDBLINDMETADATA_SEMANTIC_GAUSSIAN_ID": 20,
    "PNANOVDB_GRIDBLINDMETADATA_SEMANTIC_RANGE": 21,
    "PNANOVDB_GRIDBLINDMETADATA_SEMANTIC_VOXEL_BVH": 22,
    "PNANOVDB_GRIDBLINDMETADATA_SEMANTIC_END": 23,
    "PNANOVDB_GRIDBLINDMETADATA_SIZE": 288,
    "PNANOVDB_GRIDBLINDMETADATA_OFF_DATA_OFFSET": 0,
    "PNANOVDB_GRIDBLINDMETADATA_OFF_VALUE_COUNT": 8,
    "PNANOVDB_GRIDBLINDMETADATA_OFF_VALUE_SIZE": 16,
    "PNANOVDB_GRIDBLINDMETADATA_OFF_SEMANTIC": 20,
    "PNANOVDB_GRIDBLINDMETADATA_OFF_DATA_CLASS": 24,
    "PNANOVDB_GRIDBLINDMETADATA_OFF_DATA_TYPE": 28,
    "PNANOVDB_GRIDBLINDMETADATA_OFF_NAME": 32,
    "PNANOVDB_TREE_SIZE": 64,
    "PNANOVDB_TREE_OFF_NODE_OFFSET_LEAF": 0,
    "PNANOVDB_TREE_OFF_NODE_OFFSET_LOWER": 8,
    "PNANOVDB_TREE_OFF_NODE_OFFSET_UPPER": 16,
    "PNANOVDB_TREE_OFF_NODE_OFFSET_ROOT": 24,
    "PNANOVDB_TREE_OFF_NODE_COUNT_LEAF": 32,
    "PNANOVDB_TREE_OFF_NODE_COUNT_LOWER": 36,
    "PNANOVDB_TREE_OFF_NODE_COUNT_UPPER": 40,
    "PNANOVDB_TREE_OFF_TILE_COUNT_LOWER": 44,
    "PNANOVDB_TREE_OFF_TILE_COUNT_UPPER": 48,
    "PNANOVDB_TREE_OFF_TILE_COUNT_ROOT": 52,
    "PNANOVDB_TREE_OFF_VOXEL_COUNT": 56,
    "PNANOVDB_ROOT_BASE_SIZE": 28,
    "PNANOVDB_ROOT_OFF_BBOX_MIN": 0,
    "PNANOVDB_ROOT_OFF_BBOX_MAX": 12,
    "PNANOVDB_ROOT_OFF_TABLE_SIZE": 24,
    "PNANOVDB_ROOT_TILE_BASE_SIZE": 20,
    "PNANOVDB_ROOT_TILE_OFF_KEY": 0,
    "PNANOVDB_ROOT_TILE_OFF_CHILD": 8,
    "PNANOVDB_ROOT_TILE_OFF_STATE": 16,
    "PNANOVDB_UPPER_TABLE_COUNT": 32768,
    "PNANOVDB_UPPER_BASE_SIZE": 8224,
    "PNANOVDB_UPPER_OFF_BBOX_MIN": 0,
    "PNANOVDB_UPPER_OFF_BBOX_MAX": 12,
    "PNANOVDB_UPPER_OFF_FLAGS": 24,
    "PNANOVDB_UPPER_OFF_VALUE_MASK": 32,
    "PNANOVDB_UPPER_OFF_CHILD_MASK": 4128,
    "PNANOVDB_LOWER_TABLE_COUNT": 4096,
    "PNANOVDB_LOWER_BASE_SIZE": 1056,
    "PNANOVDB_LOWER_OFF_BBOX_MIN": 0,
    "PNANOVDB_LOWER_OFF_BBOX_MAX": 12,
    "PNANOVDB_LOWER_OFF_FLAGS": 24,
    "PNANOVDB_LOWER_OFF_VALUE_MASK": 32,
    "PNANOVDB_LOWER_OFF_CHILD_MASK": 544,
    "PNANOVDB_LEAF_TABLE_COUNT": 512,
    "PNANOVDB_LEAF_BASE_SIZE": 80,
    "PNANOVDB_LEAF_OFF_BBOX_MIN": 0,
    "PNANOVDB_LEAF_OFF_BBOX_DIF_AND_FLAGS": 12,
    "PNANOVDB_LEAF_OFF_VALUE_MASK": 16,
    "PNANOVDB_LEAF_TABLE_NEG_OFF_BBOX_DIF_AND_FLAGS": 84,
    "PNANOVDB_LEAF_TABLE_NEG_OFF_MINIMUM": 16,
    "PNANOVDB_LEAF_TABLE_NEG_OFF_QUANTUM": 12
  },
  "gridTypes": {
    "UNKNOWN": 0,
    "FLOAT": 1,
    "DOUBLE": 2,
    "INT16": 3,
    "INT32": 4,
    "INT64": 5,
    "VEC3F": 6,
    "VEC3D": 7,
    "MASK": 8,
    "HALF": 9,
    "UINT32": 10,
    "BOOLEAN": 11,
    "RGBA8": 12,
    "FP4": 13,
    "FP8": 14,
    "FP16": 15,
    "FPN": 16,
    "VEC4F": 17,
    "VEC4D": 18,
    "INDEX": 19,
    "ONINDEX": 20,
    "POINTINDEX": 23,
    "VEC3U8": 24,
    "VEC3U16": 25,
    "UINT8": 26,
    "END": 27
  },
  "constantsFields": [
    "root_off_background",
    "root_off_min",
    "root_off_max",
    "root_off_ave",
    "root_off_stddev",
    "root_size",
    "value_stride_bits",
    "table_stride",
    "root_tile_off_value",
    "root_tile_size",
    "upper_off_min",
    "upper_off_max",
    "upper_off_ave",
    "upper_off_stddev",
    "upper_off_table",
    "upper_size",
    "lower_off_min",
    "lower_off_max",
    "lower_off_ave",
    "lower_off_stddev",
    "lower_off_table",
    "lower_size",
    "leaf_off_min",
    "leaf_off_max",
    "leaf_off_ave",
    "leaf_off_stddev",
    "leaf_off_table",
    "leaf_size"
  ],
  "gridTypeConstants": {
    "UNKNOWN": {
      "root_off_background": 28,
      "root_off_min": 28,
      "root_off_max": 28,
      "root_off_ave": 28,
      "root_off_stddev": 28,
      "root_size": 32,
      "value_stride_bits": 0,
      "table_stride": 8,
      "root_tile_off_value": 20,
      "root_tile_size": 32,
      "upper_off_min": 8224,
      "upper_off_max": 8224,
      "upper_off_ave": 8224,
      "upper_off_stddev": 8224,
      "upper_off_table": 8224,
      "upper_size": 270368,
      "lower_off_min": 1056,
      "lower_off_max": 1056,
      "lower_off_ave": 1056,
      "lower_off_stddev": 1056,
      "lower_off_table": 1056,
      "lower_size": 33824,
      "leaf_off_min": 80,
      "leaf_off_max": 80,
      "leaf_off_ave": 80,
      "leaf_off_stddev": 80,
      "leaf_off_table": 96,
      "leaf_size": 96
    },
    "FLOAT": {
      "root_off_background": 28,
      "root_off_min": 32,
      "root_off_max": 36,
      "root_off_ave": 40,
      "root_off_stddev": 44,
      "root_size": 64,
      "value_stride_bits": 32,
      "table_stride": 8,
      "root_tile_off_value": 20,
      "root_tile_size": 32,
      "upper_off_min": 8224,
      "upper_off_max": 8228,
      "upper_off_ave": 8232,
      "upper_off_stddev": 8236,
      "upper_off_table": 8256,
      "upper_size": 270400,
      "lower_off_min": 1056,
      "lower_off_max": 1060,
      "lower_off_ave": 1064,
      "lower_off_stddev": 1068,
      "lower_off_table": 1088,
      "lower_size": 33856,
      "leaf_off_min": 80,
      "leaf_off_max": 84,
      "leaf_off_ave": 88,
      "leaf_off_stddev": 92,
      "leaf_off_table": 96,
      "leaf_size": 2144
    },
    "DOUBLE": {
      "root_off_background": 32,
      "root_off_min": 40,
      "root_off_max": 48,
      "root_off_ave": 56,
      "root_off_stddev": 64,
      "root_size": 96,
      "value_stride_bits": 64,
      "table_stride": 8,
      "root_tile_off_value": 24,
      "root_tile_size": 32,
      "upper_off_min": 8224,
      "upper_off_max": 8232,
      "upper_off_ave": 8240,
      "upper_off_stddev": 8248,
      "upper_off_table": 8256,
      "upper_size": 270400,
      "lower_off_min": 1056,
      "lower_off_max": 1064,
      "lower_off_ave": 1072,
      "lower_off_stddev": 1080,
      "lower_off_table": 1088,
      "lower_size": 33856,
      "leaf_off_min": 80,
      "leaf_off_max": 88,
      "leaf_off_ave": 96,
      "leaf_off_stddev": 104,
      "leaf_off_table": 128,
      "leaf_size": 4224
    },
    "INT16": {
      "root_off_background": 28,
      "root_off_min": 30,
      "root_off_max": 32,
      "root_off_ave": 36,
      "root_off_stddev": 40,
      "root_size": 64,
      "value_stride_bits": 16,
      "table_stride": 8,
      "root_tile_off_value": 20,
      "root_tile_size": 32,
      "upper_off_min": 8224,
      "upper_off_max": 8226,
      "upper_off_ave": 8228,
      "upper_off_stddev": 8232,
      "upper_off_table": 8256,
      "upper_size": 270400,
      "lower_off_min": 1056,
      "lower_off_max": 1058,
      "lower_off_ave": 1060,
      "lower_off_stddev": 1064,
      "lower_off_table": 1088,
      "lower_size": 33856,
      "leaf_off_min": 80,
      "leaf_off_max": 82,
      "leaf_off_ave": 84,
      "leaf_off_stddev": 88,
      "leaf_off_table": 96,
      "leaf_size": 1120
    },
    "INT32": {
      "root_off_background": 28,
      "root_off_min": 32,
      "root_off_max": 36,
      "root_off_ave": 40,
      "root_off_stddev": 44,
      "root_size": 64,
      "value_stride_bits": 32,
      "table_stride": 8,
      "root_tile_off_value": 20,
      "root_tile_size": 32,
      "upper_off_min": 8224,
      "upper_off_max": 8228,
      "upper_off_ave": 8232,
      "upper_off_stddev": 8236,
      "upper_off_table": 8256,
      "upper_size": 270400,
      "lower_off_min": 1056,
      "lower_off_max": 1060,
      "lower_off_ave": 1064,
      "lower_off_stddev": 1068,
      "lower_off_table": 1088,
      "lower_size": 33856,
      "leaf_off_min": 80,
      "leaf_off_max": 84,
      "leaf_off_ave": 88,
      "leaf_off_stddev": 92,
      "leaf_off_table": 96,
      "leaf_size": 2144
    },
    "INT64": {
      "root_off_background": 32,
      "root_off_min": 40,
      "root_off_max": 48,
      "root_off_ave": 56,
      "root_off_stddev": 64,
      "root_size": 96,
      "value_stride_bits": 64,
      "table_stride": 8,
      "root_tile_off_value": 24,
      "root_tile_size": 32,
      "upper_off_min": 8224,
      "upper_off_max": 8232,
      "upper_off_ave": 8240,
      "upper_off_stddev": 8248,
      "upper_off_table": 8256,
      "upper_size": 270400,
      "lower_off_min": 1056,
      "lower_off_max": 1064,
      "lower_off_ave": 1072,
      "lower_off_stddev": 1080,
      "lower_off_table": 1088,
      "lower_size": 33856,
      "leaf_off_min": 80,
      "leaf_off_max": 88,
      "leaf_off_ave": 96,
      "leaf_off_stddev": 104,
      "leaf_off_table": 128,
      "leaf_size": 4224
    },
    "VEC3F": {
      "root_off_background": 28,
      "root_off_min": 40,
      "root_off_max": 52,
      "root_off_ave": 64,
      "root_off_stddev": 68,
      "root_size": 96,
      "value_stride_bits": 96,
      "table_stride": 16,
      "root_tile_off_value": 20,
      "root_tile_size": 32,
      "upper_off_min": 8224,
      "upper_off_max": 8236,
      "upper_off_ave": 8248,
      "upper_off_stddev": 8252,
      "upper_off_table": 8256,
      "upper_size": 532544,
      "lower_off_min": 1056,
      "lower_off_max": 1068,
      "lower_off_ave": 1080,
      "lower_off_stddev": 1084,
      "lower_off_table": 1088,
      "lower_size": 66624,
      "leaf_off_min": 80,
      "leaf_off_max": 92,
      "leaf_off_ave": 104,
      "leaf_off_stddev": 108,
      "leaf_off_table": 128,
      "leaf_size": 6272
    },
    "VEC3D": {
      "root_off_background": 32,
      "root_off_min": 56,
      "root_off_max": 80,
      "root_off_ave": 104,
      "root_off_stddev": 112,
      "root_size": 128,
      "value_stride_bits": 192,
      "table_stride": 24,
      "root_tile_off_value": 24,
      "root_tile_size": 64,
      "upper_off_min": 8224,
      "upper_off_max": 8248,
      "upper_off_ave": 8272,
      "upper_off_stddev": 8280,
      "upper_off_table": 8288,
      "upper_size": 794720,
      "lower_off_min": 1056,
      "lower_off_max": 1080,
      "lower_off_ave": 1104,
      "lower_off_stddev": 1112,
      "lower_off_table": 1120,
      "lower_size": 99424,
      "leaf_off_min": 80,
      "leaf_off_max": 104,
      "leaf_off_ave": 128,
      "leaf_off_stddev": 136,
      "leaf_off_table": 160,
      "leaf_size": 12448
    },
    "MASK": {
      "root_off_background": 28,
      "root_off_min": 29,
      "root_off_max": 30,
      "root_off_ave": 31,
      "root_off_stddev": 32,
      "root_size": 64,
      "value_stride_bits": 0,
      "table_stride": 8,
      "root_tile_off_value": 20,
      "root_tile_size": 32,
      "upper_off_min": 8224,
      "upper_off_max": 8225,
      "upper_off_ave": 8226,
      "upper_off_stddev": 8227,
      "upper_off_table": 8256,
      "upper_size": 270400,
      "lower_off_min": 1056,
      "lower_off_max": 1057,
      "lower_off_ave": 1058,
      "lower_off_stddev": 1059,
      "lower_off_table": 1088,
      "lower_size": 33856,
      "leaf_off_min": 80,
      "leaf_off_max": 80,
      "leaf_off_ave": 80,
      "leaf_off_stddev": 80,
      "leaf_off_table": 96,
      "leaf_size": 96
    },
    "HALF": {
      "root_off_background": 28,
      "root_off_min": 30,
      "root_off_max": 32,
      "root_off_ave": 36,
      "root_off_stddev": 40,
      "root_size": 64,
      "value_stride_bits": 16,
      "table_stride": 8,
      "root_tile_off_value": 20,
      "root_tile_size": 32,
      "upper_off_min": 8224,
      "upper_off_max": 8226,
      "upper_off_ave": 8228,
      "upper_off_stddev": 8232,
      "upper_off_table": 8256,
      "upper_size": 270400,
      "lower_off_min": 1056,
      "lower_off_max": 1058,
      "lower_off_ave": 1060,
      "lower_off_stddev": 1064,
      "lower_off_table": 1088,
      "lower_size": 33856,
      "leaf_off_min": 80,
      "leaf_off_max": 82,
      "leaf_off_ave": 84,
      "leaf_off_stddev": 88,
      "leaf_off_table": 96,
      "leaf_size": 1120
    },
    "UINT32": {
      "root_off_background": 28,
      "root_off_min": 32,
      "root_off_max": 36,
      "root_off_ave": 40,
      "root_off_stddev": 44,
      "root_size": 64,
      "value_stride_bits": 32,
      "table_stride": 8,
      "root_tile_off_value": 20,
      "root_tile_size": 32,
      "upper_off_min": 8224,
      "upper_off_max": 8228,
      "upper_off_ave": 8232,
      "upper_off_stddev": 8236,
      "upper_off_table": 8256,
      "upper_size": 270400,
      "lower_off_min": 1056,
      "lower_off_max": 1060,
      "lower_off_ave": 1064,
      "lower_off_stddev": 1068,
      "lower_off_table": 1088,
      "lower_size": 33856,
      "leaf_off_min": 80,
      "leaf_off_max": 84,
      "leaf_off_ave": 88,
      "leaf_off_stddev": 92,
      "leaf_off_table": 96,
      "leaf_size": 2144
    },
    "BOOLEAN": {
      "root_off_background": 28,
      "root_off_min": 29,
      "root_off_max": 30,
      "root_off_ave": 31,
      "root_off_stddev": 32,
      "root_size": 64,
      "value_stride_bits": 1,
      "table_stride": 8,
      "root_tile_off_value": 20,
      "root_tile_size": 32,
      "upper_off_min": 8224,
      "upper_off_max": 8225,
      "upper_off_ave": 8226,
      "upper_off_stddev": 8227,
      "upper_off_table": 8256,
      "upper_size": 270400,
      "lower_off_min": 1056,
      "lower_off_max": 1057,
      "lower_off_ave": 1058,
      "lower_off_stddev": 1059,
      "lower_off_table": 1088,
      "lower_size": 33856,
      "leaf_off_min": 80,
      "leaf_off_max": 80,
      "leaf_off_ave": 80,
      "leaf_off_stddev": 80,
      "leaf_off_table": 96,
      "leaf_size": 160
    },
    "RGBA8": {
      "root_off_background": 28,
      "root_off_min": 32,
      "root_off_max": 36,
      "root_off_ave": 40,
      "root_off_stddev": 44,
      "root_size": 64,
      "value_stride_bits": 32,
      "table_stride": 8,
      "root_tile_off_value": 20,
      "root_tile_size": 32,
      "upper_off_min": 8224,
      "upper_off_max": 8228,
      "upper_off_ave": 8232,
      "upper_off_stddev": 8236,
      "upper_off_table": 8256,
      "upper_size": 270400,
      "lower_off_min": 1056,
      "lower_off_max": 1060,
      "lower_off_ave": 1064,
      "lower_off_stddev": 1068,
      "lower_off_table": 1088,
      "lower_size": 33856,
      "leaf_off_min": 80,
      "leaf_off_max": 84,
      "leaf_off_ave": 88,
      "leaf_off_stddev": 92,
      "leaf_off_table": 96,
      "leaf_size": 2144
    },
    "FP4": {
      "root_off_background": 28,
      "root_off_min": 32,
      "root_off_max": 36,
      "root_off_ave": 40,
      "root_off_stddev": 44,
      "root_size": 64,
      "value_stride_bits": 0,
      "table_stride": 8,
      "root_tile_off_value": 20,
      "root_tile_size": 32,
      "upper_off_min": 8224,
      "upper_off_max": 8228,
      "upper_off_ave": 8232,
      "upper_off_stddev": 8236,
      "upper_off_table": 8256,
      "upper_size": 270400,
      "lower_off_min": 1056,
      "lower_off_max": 1060,
      "lower_off_ave": 1064,
      "lower_off_stddev": 1068,
      "lower_off_table": 1088,
      "lower_size": 33856,
      "leaf_off_min": 88,
      "leaf_off_max": 90,
      "leaf_off_ave": 92,
      "leaf_off_stddev": 94,
      "leaf_off_table": 96,
      "leaf_size": 352
    },
    "FP8": {
      "root_off_background": 28,
      "root_off_min": 32,
      "root_off_max": 36,
      "root_off_ave": 40,
      "root_off_stddev": 44,
      "root_size": 64,
      "value_stride_bits": 0,
      "table_stride": 8,
      "root_tile_off_value": 20,
      "root_tile_size": 32,
      "upper_off_min": 8224,
      "upper_off_max": 8228,
      "upper_off_ave": 8232,
      "upper_off_stddev": 8236,
      "upper_off_table": 8256,
      "upper_size": 270400,
      "lower_off_min": 1056,
      "lower_off_max": 1060,
      "lower_off_ave": 1064,
      "lower_off_stddev": 1068,
      "lower_off_table": 1088,
      "lower_size": 33856,
      "leaf_off_min": 88,
      "leaf_off_max": 90,
      "leaf_off_ave": 92,
      "leaf_off_stddev": 94,
      "leaf_off_table": 96,
      "leaf_size": 608
    },
    "FP16": {
      "root_off_background": 28,
      "root_off_min": 32,
      "root_off_max": 36,
      "root_off_ave": 40,
      "root_off_stddev": 44,
      "root_size": 64,
      "value_stride_bits": 0,
      "table_stride": 8,
      "root_tile_off_value": 20,
      "root_tile_size": 32,
      "upper_off_min": 8224,
      "upper_off_max": 8228,
      "upper_off_ave": 8232,
      "upper_off_stddev": 8236,
      "upper_off_table": 8256,
      "upper_size": 270400,
      "lower_off_min": 1056,
      "lower_off_max": 1060,
      "lower_off_ave": 1064,
      "lower_off_stddev": 1068,
      "lower_off_table": 1088,
      "lower_size": 33856,
      "leaf_off_min": 88,
      "leaf_off_max": 90,
      "leaf_off_ave": 92,
      "leaf_off_stddev": 94,
      "leaf_off_table": 96,
      "leaf_size": 1120
    },
    "FPN": {
      "root_off_background": 28,
      "root_off_min": 32,
      "root_off_max": 36,
      "root_off_ave": 40,
      "root_off_stddev": 44,
      "root_size": 64,
      "value_stride_bits": 0,
      "table_stride": 8,
      "root_tile_off_value": 20,
      "root_tile_size": 32,
      "upper_off_min": 8224,
      "upper_off_max": 8228,
      "upper_off_ave": 8232,
      "upper_off_stddev": 8236,
      "upper_off_table": 8256,
      "upper_size": 270400,
      "lower_off_min": 1056,
      "lower_off_max": 1060,
      "lower_off_ave": 1064,
      "lower_off_stddev": 1068,
      "lower_off_table": 1088,
      "lower_size": 33856,
      "leaf_off_min": 88,
      "leaf_off_max": 90,
      "leaf_off_ave": 92,
      "leaf_off_stddev": 94,
      "leaf_off_table": 96,
      "leaf_size": 96
    },
    "VEC4F": {
      "root_off_background": 28,
      "root_off_min": 44,
      "root_off_max": 60,
      "root_off_ave": 76,
      "root_off_stddev": 80,
      "root_size": 96,
      "value_stride_bits": 128,
      "table_stride": 16,
      "root_tile_off_value": 20,
      "root_tile_size": 64,
      "upper_off_min": 8224,
      "upper_off_max": 8240,
      "upper_off_ave": 8256,
      "upper_off_stddev": 8260,
      "upper_off_table": 8288,
      "upper_size": 532576,
      "lower_off_min": 1056,
      "lower_off_max": 1072,
      "lower_off_ave": 1088,
      "lower_off_stddev": 1092,
      "lower_off_table": 1120,
      "lower_size": 66656,
      "leaf_off_min": 80,
      "leaf_off_max": 96,
      "leaf_off_ave": 112,
      "leaf_off_stddev": 116,
      "leaf_off_table": 128,
      "leaf_size": 8320
    },
    "VEC4D": {
      "root_off_background": 32,
      "root_off_min": 64,
      "root_off_max": 96,
      "root_off_ave": 128,
      "root_off_stddev": 136,
      "root_size": 160,
      "value_stride_bits": 256,
      "table_stride": 32,
      "root_tile_off_value": 24,
      "root_tile_size": 64,
      "upper_off_min": 8224,
      "upper_off_max": 8256,
      "upper_off_ave": 8288,
      "upper_off_stddev": 8296,
      "upper_off_table": 8320,
      "upper_size": 1056896,
      "lower_off_min": 1056,
      "lower_off_max": 1088,
      "lower_off_ave": 1120,
      "lower_off_stddev": 1128,
      "lower_off_table": 1152,
      "lower_size": 132224,
      "leaf_off_min": 80,
      "leaf_off_max": 112,
      "leaf_off_ave": 144,
      "leaf_off_stddev": 152,
      "leaf_off_table": 160,
      "leaf_size": 16544
    },
    "INDEX": {
      "root_off_background": 32,
      "root_off_min": 40,
      "root_off_max": 48,
      "root_off_ave": 56,
      "root_off_stddev": 64,
      "root_size": 96,
      "value_stride_bits": 0,
      "table_stride": 8,
      "root_tile_off_value": 24,
      "root_tile_size": 32,
      "upper_off_min": 8224,
      "upper_off_max": 8232,
      "upper_off_ave": 8240,
      "upper_off_stddev": 8248,
      "upper_off_table": 8256,
      "upper_size": 270400,
      "lower_off_min": 1056,
      "lower_off_max": 1064,
      "lower_off_ave": 1072,
      "lower_off_stddev": 1080,
      "lower_off_table": 1088,
      "lower_size": 33856,
      "leaf_off_min": 80,
      "leaf_off_max": 80,
      "leaf_off_ave": 80,
      "leaf_off_stddev": 80,
      "leaf_off_table": 80,
      "leaf_size": 96
    },
    "ONINDEX": {
      "root_off_background": 32,
      "root_off_min": 40,
      "root_off_max": 48,
      "root_off_ave": 56,
      "root_off_stddev": 64,
      "root_size": 96,
      "value_stride_bits": 0,
      "table_stride": 8,
      "root_tile_off_value": 24,
      "root_tile_size": 32,
      "upper_off_min": 8224,
      "upper_off_max": 8232,
      "upper_off_ave": 8240,
      "upper_off_stddev": 8248,
      "upper_off_table": 8256,
      "upper_size": 270400,
      "lower_off_min": 1056,
      "lower_off_max": 1064,
      "lower_off_ave": 1072,
      "lower_off_stddev": 1080,
      "lower_off_table": 1088,
      "lower_size": 33856,
      "leaf_off_min": 80,
      "leaf_off_max": 80,
      "leaf_off_ave": 80,
      "leaf_off_stddev": 80,
      "leaf_off_table": 80,
      "leaf_size": 96
    },
    "TYPE_21": {
      "root_off_background": 28,
      "root_off_min": 28,
      "root_off_max": 28,
      "root_off_ave": 28,
      "root_off_stddev": 28,
      "root_size": 32,
      "value_stride_bits": 0,
      "table_stride": 8,
      "root_tile_off_value": 20,
      "root_tile_size": 32,
      "upper_off_min": 8224,
      "upper_off_max": 8224,
      "upper_off_ave": 8224,
      "upper_off_stddev": 8224,
      "upper_off_table": 8224,
      "upper_size": 270368,
      "lower_off_min": 1056,
      "lower_off_max": 1056,
      "lower_off_ave": 1056,
      "lower_off_stddev": 1056,
      "lower_off_table": 1056,
      "lower_size": 33824,
      "leaf_off_min": 80,
      "leaf_off_max": 80,
      "leaf_off_ave": 80,
      "leaf_off_stddev": 80,
      "leaf_off_table": 96,
      "leaf_size": 96
    },
    "TYPE_22": {
      "root_off_background": 28,
      "root_off_min": 28,
      "root_off_max": 28,
      "root_off_ave": 28,
      "root_off_stddev": 28,
      "root_size": 32,
      "value_stride_bits": 0,
      "table_stride": 8,
      "root_tile_off_value": 20,
      "root_tile_size": 32,
      "upper_off_min": 8224,
      "upper_off_max": 8224,
      "upper_off_ave": 8224,
      "upper_off_stddev": 8224,
      "upper_off_table": 8224,
      "upper_size": 270368,
      "lower_off_min": 1056,
      "lower_off_max": 1056,
      "lower_off_ave": 1056,
      "lower_off_stddev": 1056,
      "lower_off_table": 1056,
      "lower_size": 33824,
      "leaf_off_min": 80,
      "leaf_off_max": 80,
      "leaf_off_ave": 80,
      "leaf_off_stddev": 80,
      "leaf_off_table": 96,
      "leaf_size": 96
    },
    "POINTINDEX": {
      "root_off_background": 32,
      "root_off_min": 40,
      "root_off_max": 48,
      "root_off_ave": 56,
      "root_off_stddev": 64,
      "root_size": 96,
      "value_stride_bits": 16,
      "table_stride": 8,
      "root_tile_off_value": 24,
      "root_tile_size": 32,
      "upper_off_min": 8224,
      "upper_off_max": 8232,
      "upper_off_ave": 8240,
      "upper_off_stddev": 8248,
      "upper_off_table": 8256,
      "upper_size": 270400,
      "lower_off_min": 1056,
      "lower_off_max": 1064,
      "lower_off_ave": 1072,
      "lower_off_stddev": 1080,
      "lower_off_table": 1088,
      "lower_size": 33856,
      "leaf_off_min": 80,
      "leaf_off_max": 88,
      "leaf_off_ave": 96,
      "leaf_off_stddev": 96,
      "leaf_off_table": 96,
      "leaf_size": 1120
    },
    "VEC3U8": {
      "root_off_background": 28,
      "root_off_min": 31,
      "root_off_max": 34,
      "root_off_ave": 40,
      "root_off_stddev": 44,
      "root_size": 64,
      "value_stride_bits": 24,
      "table_stride": 8,
      "root_tile_off_value": 20,
      "root_tile_size": 32,
      "upper_off_min": 8224,
      "upper_off_max": 8227,
      "upper_off_ave": 8232,
      "upper_off_stddev": 8236,
      "upper_off_table": 8256,
      "upper_size": 270400,
      "lower_off_min": 1056,
      "lower_off_max": 1059,
      "lower_off_ave": 1064,
      "lower_off_stddev": 1068,
      "lower_off_table": 1088,
      "lower_size": 33856,
      "leaf_off_min": 80,
      "leaf_off_max": 83,
      "leaf_off_ave": 88,
      "leaf_off_stddev": 92,
      "leaf_off_table": 96,
      "leaf_size": 1632
    },
    "VEC3U16": {
      "root_off_background": 28,
      "root_off_min": 34,
      "root_off_max": 40,
      "root_off_ave": 48,
      "root_off_stddev": 52,
      "root_size": 64,
      "value_stride_bits": 48,
      "table_stride": 8,
      "root_tile_off_value": 20,
      "root_tile_size": 32,
      "upper_off_min": 8224,
      "upper_off_max": 8230,
      "upper_off_ave": 8236,
      "upper_off_stddev": 8240,
      "upper_off_table": 8256,
      "upper_size": 270400,
      "lower_off_min": 1056,
      "lower_off_max": 1062,
      "lower_off_ave": 1068,
      "lower_off_stddev": 1072,
      "lower_off_table": 1088,
      "lower_size": 33856,
      "leaf_off_min": 80,
      "leaf_off_max": 86,
      "leaf_off_ave": 92,
      "leaf_off_stddev": 96,
      "leaf_off_table": 128,
      "leaf_size": 3200
    },
    "UINT8": {
      "root_off_background": 28,
      "root_off_min": 29,
      "root_off_max": 30,
      "root_off_ave": 32,
      "root_off_stddev": 36,
      "root_size": 64,
      "value_stride_bits": 8,
      "table_stride": 8,
      "root_tile_off_value": 20,
      "root_tile_size": 32,
      "upper_off_min": 8224,
      "upper_off_max": 8225,
      "upper_off_ave": 8228,
      "upper_off_stddev": 8232,
      "upper_off_table": 8256,
      "upper_size": 270400,
      "lower_off_min": 1056,
      "lower_off_max": 1057,
      "lower_off_ave": 1060,
      "lower_off_stddev": 1064,
      "lower_off_table": 1088,
      "lower_size": 33856,
      "leaf_off_min": 80,
      "leaf_off_max": 81,
      "leaf_off_ave": 84,
      "leaf_off_stddev": 88,
      "leaf_off_table": 96,
      "leaf_size": 608
    },
    "END": {
      "root_off_background": 28,
      "root_off_min": 28,
      "root_off_max": 28,
      "root_off_ave": 28,
      "root_off_stddev": 28,
      "root_size": 32,
      "value_stride_bits": 0,
      "table_stride": 8,
      "root_tile_off_value": 20,
      "root_tile_size": 32,
      "upper_off_min": 8224,
      "upper_off_max": 8224,
      "upper_off_ave": 8224,
      "upper_off_stddev": 8224,
      "upper_off_table": 8224,
      "upper_size": 270368,
      "lower_off_min": 1056,
      "lower_off_max": 1056,
      "lower_off_ave": 1056,
      "lower_off_stddev": 1056,
      "lower_off_table": 1056,
      "lower_size": 33824,
      "leaf_off_min": 80,
      "leaf_off_max": 80,
      "leaf_off_ave": 80,
      "leaf_off_stddev": 80,
      "leaf_off_table": 96,
      "leaf_size": 96
    }
  },
  "auxArrays": {
    "grid_type_value_strides_bits": [
      0,
      32,
      64,
      16,
      32,
      64,
      96,
      192,
      0,
      16,
      32,
      1,
      32,
      4,
      8,
      16,
      0,
      128,
      256,
      0,
      0,
      0,
      0,
      16,
      24,
      48,
      8,
      0
    ],
    "grid_type_table_strides_bits": [
      64,
      64,
      64,
      64,
      64,
      64,
      128,
      192,
      64,
      64,
      64,
      64,
      64,
      64,
      64,
      64,
      64,
      128,
      256,
      64,
      64,
      64,
      64,
      64,
      64,
      64,
      64,
      64
    ],
    "grid_type_minmax_strides_bits": [
      0,
      32,
      64,
      16,
      32,
      64,
      96,
      192,
      8,
      16,
      32,
      8,
      32,
      32,
      32,
      32,
      32,
      128,
      256,
      64,
      64,
      0,
      0,
      64,
      24,
      48,
      8,
      0
    ],
    "grid_type_minmax_aligns_bits": [
      0,
      32,
      64,
      16,
      32,
      64,
      32,
      64,
      8,
      16,
      32,
      8,
      32,
      32,
      32,
      32,
      32,
      32,
      64,
      64,
      64,
      0,
      0,
      64,
      8,
      16,
      8,
      0
    ],
    "grid_type_stat_strides_bits": [
      0,
      32,
      64,
      32,
      32,
      64,
      32,
      64,
      8,
      32,
      32,
      8,
      32,
      32,
      32,
      32,
      32,
      32,
      64,
      64,
      64,
      0,
      0,
      64,
      32,
      32,
      32,
      0
    ],
    "grid_type_leaf_type": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      0,
      0,
      1,
      0,
      2,
      2,
      2,
      2,
      0,
      0,
      3,
      3,
      0,
      0,
      5,
      0,
      0,
      0,
      0
    ]
  }
} as const;
