/**
 * Raw-WebGPU test-harness footer, appended after the vendored
 * `pnanovdb.wgsl` module text at runtime (see main.ts). Declares the storage
 * binding the module's own header comment asks every consumer to provide
 * (`nanovdb_buffer`), plus two `@compute` entry points that drive
 * `pnanovdb_readaccessor_get_value_float` / `pnanovdb_readaccessor_is_active`
 * / `pnanovdb_sample_trilinear_typed` over flat coordinate buffers, so the
 * CPU reference (`nanovdb-wgsl`'s package-exported `readValue`/
 * `sampleTrilinear`, see `main.ts`) and the GPU shader can be compared
 * value-for-value.
 *
 * Binding layout (explicit, non-'auto', built in main.ts):
 *   @group(0): nanovdb_buffer (0), harness_grid_type (1) — shared by both
 *     entry points.
 *   @group(1): harness_probe_coords (0), harness_probe_value_out (1),
 *     harness_probe_active_out (2) — probe entry point only.
 *   @group(2): harness_tri_points (0), harness_tri_value_out (1) —
 *     trilinear entry point only (main.ts supplies an empty placeholder
 *     bind group layout at index 1 for this pipeline, since
 *     `GPUPipelineLayout.bindGroupLayouts` is positional and this entry
 *     point skips @group(1)).
 *
 * Naming: every harness-owned identifier is prefixed `harness_` to avoid
 * colliding with pnanovdb.wgsl's own names. Note `active` is a reserved
 * WGSL keyword (a Phase 1 finding, see docs/handoffs/PHASE-1.md) — hence
 * `is_act` below, not `active`.
 */
export const HARNESS_FOOTER_WGSL = /* wgsl */ `
// ===========================================================================
// WebVDB Phase 2 GPU-parity test-harness footer (generated by
// examples/src/harness/shader-footer.ts, appended after the vendored
// pnanovdb.wgsl module text).
// ===========================================================================

@group(0) @binding(0) var<storage, read> nanovdb_buffer : array<u32>;
@group(0) @binding(1) var<storage, read> harness_grid_type : array<u32>;

@group(1) @binding(0) var<storage, read> harness_probe_coords : array<i32>;
@group(1) @binding(1) var<storage, read_write> harness_probe_value_out : array<f32>;
@group(1) @binding(2) var<storage, read_write> harness_probe_active_out : array<u32>;

@group(2) @binding(0) var<storage, read> harness_tri_points : array<f32>;
@group(2) @binding(1) var<storage, read_write> harness_tri_value_out : array<f32>;

@compute @workgroup_size(64)
fn harness_main_probe(@builtin(global_invocation_id) gid : vec3<u32>) {
  let i = gid.x;
  if (i >= arrayLength(&harness_probe_value_out)) {
    return;
  }
  let base = i * 3u;
  let ijk = vec3<i32>(
    harness_probe_coords[base],
    harness_probe_coords[base + 1u],
    harness_probe_coords[base + 2u],
  );

  let grid_type = harness_grid_type[0u];
  let buf = pnanovdb_make_buffer(0u, arrayLength(&nanovdb_buffer));
  let grid = pnanovdb_grid_handle_t(0u);
  let tree = pnanovdb_grid_get_tree(grid);
  let root = pnanovdb_tree_get_root(buf, tree);
  var acc : pnanovdb_readaccessor_t;
  pnanovdb_readaccessor_init(&acc, root);

  let value = pnanovdb_readaccessor_get_value_float(grid_type, buf, &acc, ijk);
  let is_act = pnanovdb_readaccessor_is_active(grid_type, buf, &acc, ijk);

  harness_probe_value_out[i] = value;
  harness_probe_active_out[i] = select(0u, 1u, is_act);
}

@compute @workgroup_size(64)
fn harness_main_trilinear(@builtin(global_invocation_id) gid : vec3<u32>) {
  let i = gid.x;
  if (i >= arrayLength(&harness_tri_value_out)) {
    return;
  }
  let base = i * 3u;
  let xyz = vec3<f32>(
    harness_tri_points[base],
    harness_tri_points[base + 1u],
    harness_tri_points[base + 2u],
  );

  let grid_type = harness_grid_type[0u];
  let buf = pnanovdb_make_buffer(0u, arrayLength(&nanovdb_buffer));
  let grid = pnanovdb_grid_handle_t(0u);
  let tree = pnanovdb_grid_get_tree(grid);
  let root = pnanovdb_tree_get_root(buf, tree);
  var acc : pnanovdb_readaccessor_t;
  pnanovdb_readaccessor_init(&acc, root);

  harness_tri_value_out[i] = pnanovdb_sample_trilinear_typed(grid_type, buf, &acc, xyz);
}
`;
